// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPUMpNI11BCFvrnwrkrgj7SEZJTy2_2Vw',
    appId: '1:354407730492:web:40ab97e021526ed5732239',
    messagingSenderId: '354407730492',
    projectId: 'e-commerce-8e85a',
    authDomain: 'e-commerce-8e85a.firebaseapp.com',
    storageBucket: 'e-commerce-8e85a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7IbWkaVJFqL90nL_ZTco1d9fuUSfMtXY',
    appId: '1:354407730492:android:395e2880c44f6601732239',
    messagingSenderId: '354407730492',
    projectId: 'e-commerce-8e85a',
    storageBucket: 'e-commerce-8e85a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmZVaVrs4pBaD82DKszkbnwpJRj0Ei8Wk',
    appId: '1:354407730492:ios:9b8f516104dc7f83732239',
    messagingSenderId: '354407730492',
    projectId: 'e-commerce-8e85a',
    storageBucket: 'e-commerce-8e85a.firebasestorage.app',
    androidClientId: '354407730492-2gsho489u5vraa8a3aetl5fl60ab429c.apps.googleusercontent.com',
    iosClientId: '354407730492-4gcpopo3rnu47qi1pposvphl53ht1t08.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmZVaVrs4pBaD82DKszkbnwpJRj0Ei8Wk',
    appId: '1:354407730492:ios:9b8f516104dc7f83732239',
    messagingSenderId: '354407730492',
    projectId: 'e-commerce-8e85a',
    storageBucket: 'e-commerce-8e85a.firebasestorage.app',
    androidClientId: '354407730492-2gsho489u5vraa8a3aetl5fl60ab429c.apps.googleusercontent.com',
    iosClientId: '354407730492-4gcpopo3rnu47qi1pposvphl53ht1t08.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPUMpNI11BCFvrnwrkrgj7SEZJTy2_2Vw',
    appId: '1:354407730492:web:01e8d66c090c6152732239',
    messagingSenderId: '354407730492',
    projectId: 'e-commerce-8e85a',
    authDomain: 'e-commerce-8e85a.firebaseapp.com',
    storageBucket: 'e-commerce-8e85a.firebasestorage.app',
  );
}
